# Generated by Django 3.2.25 on 2025-08-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='Unique identifier for the run', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Human-readable name for the run', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the optimization run')),
                ('algorithm', models.CharField(choices=[('GA', 'Genetic Algorithm'), ('NSGA2', 'NSGA-II'), ('MOEA', 'Multi-Objective Evolutionary Algorithm')], default='GA', max_length=20)),
                ('model', models.CharField(choices=[('CASCADE', 'Cascade Model'), ('CUSTOM', 'Custom Model')], default='CASCADE', max_length=20)),
                ('population_size', models.IntegerField()),
                ('generations', models.IntegerField()),
                ('objectives', models.JSONField(default=list, help_text='List of objective names')),
                ('trace_name', models.CharField(blank=True, max_length=255)),
                ('trace_sets', models.JSONField(default=dict, help_text='Trace sets configuration for comparative studies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('total_designs_evaluated', models.IntegerField(default=0)),
                ('pareto_front_size', models.IntegerField(default=0)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('results_directory', models.CharField(blank=True, max_length=500)),
                ('analytics_directory', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparativeStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('shared_parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_studies_a', to='api.optimizationrun')),
                ('run_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_studies_b', to='api.optimizationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_count', models.IntegerField()),
                ('attention_count', models.IntegerField()),
                ('sparse_count', models.IntegerField()),
                ('convolution_count', models.IntegerField()),
                ('execution_time_ms', models.FloatField()),
                ('energy_mj', models.FloatField()),
                ('additional_metrics', models.JSONField(blank=True, default=dict)),
                ('is_pareto_optimal', models.BooleanField(default=False)),
                ('pareto_rank', models.IntegerField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_time_seconds', models.FloatField(blank=True, null=True)),
                ('context_file_path', models.CharField(blank=True, max_length=500)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_points', to='api.optimizationrun')),
            ],
            options={
                'ordering': ['run', 'execution_time_ms'],
                'unique_together': {('run', 'gpu_count', 'attention_count', 'sparse_count', 'convolution_count')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_type', models.CharField(choices=[('rule_mining', 'Association Rule Mining'), ('distance_correlation', 'Distance Correlation'), ('pareto_analysis', 'Pareto Front Analysis'), ('sensitivity', 'Sensitivity Analysis')], max_length=30)),
                ('results_data', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computation_time_seconds', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_results', to='api.optimizationrun')),
            ],
            options={
                'ordering': ['run', 'analytics_type'],
                'unique_together': {('run', 'analytics_type')},
            },
        ),
    ]
